import type { Metadata } from "next";
import { DM_Sans as Sans } from "next/font/google";
import "./globals.css";

const sans = Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased h-screen " + sans.className}>
        {children}
      </body>
    </html>
  );
}
